### test
POST http://localhost:5000/user/signup
Content-Type: application/json

{
    "email":"talktomeself@gmail.com",
    "username":"z",
    "password":"z"
}



### test
POST http://localhost:5000/user/signup
Content-Type: application/json

{
    "email":"ce",
    "username":"b",
    "password":"b"
}


### test
POST http://localhost:5000/user/signin
Content-Type: application/json

{ 
    "username":"b",
    "password":"abc"
}




### test
POST http://localhost:5000/user/confirm
Content-Type: application/json

{ 
    "verifyingToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InoiLCJlbWFpbCI6InRhbGt0b21lc2VsZkBnbWFpbC5jb20iLCJpYXQiOjE2MDg2NTQwMjR9.kEsQ1VzBeOL-19Ok-W6f2jW2R1O-tfXCiDisfKLiZpw"
}


### test x
POST http://localhost:5000/user/signin
Content-Type: application/json

{ 
    "username":"x",
    "password":"x",
    "verifyingToken":""
}



### FORGOT password
PUT http://localhost:5000/user/forget
Content-Type: application/json

{ 
    "email":"talktomeself@gmail.com"
}



### FORGOT password
POST http://localhost:5000/user/forget
Content-Type: application/json

{ 
    "email":"r"
}





### RESET password
POST http://localhost:5000/user/reset
Content-Type: application/json

{ 
    "email":"talktomeself@gmail.com",
    "resetLink":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRhbGt0b21lc2VsZkBnbWFpbC5jb20iLCJpYXQiOjE2MDg2MTQ4MjZ9.OoZ3bEUrUKxY4LH2XtUCN3QOUzw-RkqUxziQWJFateU",
    "newPassword":"x"
}










### see inbox
GET http://localhost:3000/user/inbox/5fbc70f7a484c65004b44106
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmJjNzBmN2E0ODRjNjUwMDRiNDQxMDYiLCJpYXQiOjE2MDYxODUzMjl9.dT9qTuiYQE6BcyCt7jAI1yZH1kXY9M9-1UOhMjUx2do


### see profile
GET http://localhost:5000/user/profile
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQxMDU1NTI0OWExZTA4NzQ1MzEyYzYiLCJpYXQiOjE2MDgyNzI5NjB9.ray6T78YYLynE3ll11E0fmApGW8L3T1Pv7O9IxtDbm8


### change profile
PUT  http://localhost:5000/user/profile
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQxMDU1NTI0OWExZTA4NzQ1MzEyYzYiLCJpYXQiOjE2MDgyNzI5NjB9.ray6T78YYLynE3ll11E0fmApGW8L3T1Pv7O9IxtDbm8

{
    "fullname":"amat sitanggang"
}



### DEMO 
GET  http://localhost:5000/user/jesting
Content-Type: application/json

{
    "stupid":"moronic",
    "moron":"stupidity"
}



### DEMO 
GET  http://localhost:5000/halloffame
Content-Type: application/json




