### LOGIN user
POST http://localhost:5000/user/signin
Content-Type: application/json

{
    "username":"abdc",
    "password":"xxx"
}


### SEE profile
GET http://localhost:5000/user/profile/5fd10555249a1e08745312c6
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQxMDU1NTI0OWExZTA4NzQ1MzEyYzYiLCJpYXQiOjE2MDc1NzMzNzZ9.CA57QwuPNwhuVc6864xbRxfwwJBoSfynmIot4DI4G9U


### EDIT profile
PUT http://localhost:5000/user/profile/5fd10555249a1e08745312c6
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQxMDU1NTI0OWExZTA4NzQ1MzEyYzYiLCJpYXQiOjE2MDc1NzMzNzZ9.CA57QwuPNwhuVc6864xbRxfwwJBoSfynmIot4DI4G9U

{
   "fullname":"samuji parangin" 
}


### SUBMIT participation
POST http://localhost:5000/user/submit
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmU5NjI0ODg1OTNmMjI5ZjgzNzMxNTUiLCJyb2xlIjoidXNlciIsImlhdCI6MTYwOTEzNTA1OX0.jiZ35_mLyZWGffASg7y5cksrpIJQVo1EhsBQLtAEyoE

{
    "tournamentName":"dota2"
}


### SUBMIT group
POST http://localhost:5000/user/submitGroup
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmU5NjI0ODg1OTNmMjI5ZjgzNzMxNTUiLCJyb2xlIjoidXNlciIsImlhdCI6MTYwOTEzNTA1OX0.jiZ35_mLyZWGffASg7y5cksrpIJQVo1EhsBQLtAEyoE

{
    "tournamentName":"elderscrollonline",
    "groupName":"porcupinetree"
}


### SEE notification
GET http://localhost:5000/user/inboxNotifications/5fd10555249a1e08745312c6
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQxMDU1NTI0OWExZTA4NzQ1MzEyYzYiLCJpYXQiOjE2MDc1NzMzNzZ9.CA57QwuPNwhuVc6864xbRxfwwJBoSfynmIot4DI4G9U


### SEE group
GET http://localhost:5000/user/group
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmVjMmZjZGM0M2Q5YTMxNjA0MTYyMjQiLCJyb2xlIjoidXNlciIsImlhdCI6MTYwOTQ0MjY2Mn0.uOMUux0-uigk5Emx9iiwiBXOpEIh4YI3Z5JxpLZ9wJc


### SEE inbox
GET http://localhost:5000/user/inbox/5fd10555249a1e08745312c6
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQxMDU1NTI0OWExZTA4NzQ1MzEyYzYiLCJpYXQiOjE2MDc1NzMzNzZ9.CA57QwuPNwhuVc6864xbRxfwwJBoSfynmIot4DI4G9U



### CREATE group
POST http://localhost:5000/user/createGroup/5fd10555249a1e08745312c6
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQxMDU1NTI0OWExZTA4NzQ1MzEyYzYiLCJpYXQiOjE2MDc1NzMzNzZ9.CA57QwuPNwhuVc6864xbRxfwwJBoSfynmIot4DI4G9U

{
      "groupName":"cityneon"
}



### DELETE group
DELETE http://localhost:5000/user/demolishGroup/5fd10555249a1e08745312c6
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQxMDU1NTI0OWExZTA4NzQ1MzEyYzYiLCJpYXQiOjE2MDc1NzMzNzZ9.CA57QwuPNwhuVc6864xbRxfwwJBoSfynmIot4DI4G9U

{
      "groupName":"cityneon"
}



### DELETE group
DELETE http://localhost:5000/user/demolishGroup/5fd10555249a1e08745312c6
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmQxMDU1NTI0OWExZTA4NzQ1MzEyYzYiLCJpYXQiOjE2MDc1NzMzNzZ9.CA57QwuPNwhuVc6864xbRxfwwJBoSfynmIot4DI4G9U

{
      "_id":"5fd5984cadd4e049543cf761"
}




### RECRUIT group
PUT http://localhost:5000/user/groupRecruit
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmVjMmZjZGM0M2Q5YTMxNjA0MTYyMjQiLCJyb2xlIjoidXNlciIsImlhdCI6MTYwOTU5MTY4MH0.QPOsQMzmbBfa-p6YQjHM8PYHvxgTYLR6fwZsNoUoX5A

{   
      "_userId":"5ff05a5ee5569c36ac3de366"   
}



### KICK group
PUT http://localhost:5000/user/groupKick
Content-Type: application/json
access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmVjMmZjZGM0M2Q5YTMxNjA0MTYyMjQiLCJyb2xlIjoidXNlciIsImlhdCI6MTYwOTU5MTY4MH0.QPOsQMzmbBfa-p6YQjHM8PYHvxgTYLR6fwZsNoUoX5A

{   
     
      "_userId":"5ff05a5ee5569c36ac3de366"
      
}
